package gradeservice.model;
// Generated May 11, 2016 1:03:45 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;

/**
 * Mark generated by hbm2java
 */
@Entity
@Table(name = "Mark", schema = "dbo", catalog = "WSAppDB2"
)
@XmlAccessorType(XmlAccessType.FIELD)
public class Mark implements java.io.Serializable {

    //
    
    private int id;
    private Student student;
    private Subject subject;
    private String name;
    private Double mark;

    public Mark() {
    }

    public Mark(int id) {
        this.id = id;
    }

    public Mark(int id, Student student, Subject subject, String name, Double mark) {
        this.id = id;
        this.student = student;
        this.subject = subject;
        this.name = name;
        this.mark = mark;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "student_id")
    public Student getStudent() {
        return this.student;
    }

    public void setStudent(Student student) {
        this.student = student;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "subject_id")
    public Subject getSubject() {
        return this.subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    @Column(name = "name", length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "mark", precision = 53, scale = 0)
    public Double getMark() {
        return this.mark;
    }

    public void setMark(Double mark) {
        this.mark = mark;
    }

}
